### ISSUE TITLE
Can't see the display

### ISSUE THREAD

**Issue by bash550** [Ham62/XMPlayDiscordStatus#1]
After putting both files in the plugin folder, nothing happens. Is there something I am doing wrong, or is there a problem with the files?

**Comment by Ham62** [comment]
After you copy the files into the folder you'll need to go into XMPlay's "Options and stuff" and click on "Plugins". In the drop down box under "DSP and general plugins" you should see "XMPlay Discord Status" listed. Select that and click the add button.

![LoadedPlugin](https://user-images.githubusercontent.com/16859496/95030334-b524e880-0674-11eb-8a03-c3c3cbd4045d.png)

If you see it in the list of plugins like in the screenshot it should be working.
