### ISSUE TITLE
Attempting to build with VS2019 does not work

### ISSUE THREAD

**Issue by ztgasdf** [Ham62/XMPlayDiscordStatus#2]
*disclaimer: i do not know a single bit of coding*

This is a great plugin, but I wanted to change a few values for myself (mainly changing the asset icons and what metadata is displayed), so I cloned and tried building without changing anything as a test, but it gave me this error:

`XMPlayDiscordStatus\source\XMPlayDiscordStatus.vcxproj : warning  : The build tools for Visual Studio 2013 - Windows XP (v120_xp) cannot be found. Install Visual Studio 2013 - Windows XP (v120_xp) to build using the Visual Studio 2013 - Windows XP (v120_xp) build tools.`

I didn't have that on me and I don't really have the disk space for another version of Visual Studio, so I decided to just change the platform toolset and the SDK version to what is currently on my computer. [SDK version 10.0.19041.0, Visual Studio 2019 (v142)]
Afterwords, I tried building, but it failed with 26 errors, 24 being in `rpc.h` and 2 being in `main.cpp`.

Here's log one: [build1.txt](https://github.com/Ham62/XMPlayDiscordStatus/files/6673131/build1.txt)

I did a little bit of rudimentary research, and apparently I can get rid of the 24 errors by adding `#pragma once` to the beginning of the header, so I went and did that, and I tried building once again. This time it failed with only two errors, the same two that were in `main.cpp`.

Log two: [build2.txt](https://github.com/Ham62/XMPlayDiscordStatus/files/6673143/build2.txt)

I looked up what error C2440 was about, and I found this [link](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?view=msvc-160) and I decided to attempt to fix it by changing these two lines https://github.com/Ham62/XMPlayDiscordStatus/blob/b0c86ccbb2dcbf1031d0ea74c35ab63785598e29/source/main.cpp#L110-L111

with

```cpp
const char* pszFirstLine = "No tracks playing.";
const char* pszSecondLine = "";
```
and tried building again. This time, it works! But... upon loading the plugin in XMPlay, the program crashes. Upon debugging, I found this: ![image](https://user-images.githubusercontent.com/83559531/122471911-da048600-cf8d-11eb-8328-fd103d7eb288.png)

This is at https://github.com/Ham62/XMPlayDiscordStatus/blob/b0c86ccbb2dcbf1031d0ea74c35ab63785598e29/source/rpc.cpp#L58

At this point, I'm at a standstill and I don't know what to do from here. Thank you once again, and sorry for the trouble!

**Comment by Ham62** [comment]
I don't have VS 2019 here, but from what I can see it looks like the SDK upgrade changed some of the compile parameters which is causing the issues with those two strings. Doing some digging it looks like if you can find the compiler switches for the project try and find the option /Zc:strictStrings and replace it with /Zc:strictStrings- to turn off that check.

If that doesn't work or you can't find the setting, one thing you can try doing is changing line 69 from
```cpp
static char *pszFirstLine, *pszSecondLine;
```
to
```cpp
const char *pszFirstLine, *pszSecondLine;
```
and see if that compiles and runs.

The changes you did on lines 110 and 111 earlier are actually creating a new variable of the same name and not initializing the correct strings being passed to the UpdatePresence() function, this is why it was crashing after you made the change. Make sure you change those back before running it again with either of the solutions above.

**Comment by ztgasdf** [comment]
It worked, it worked, IT WORKED! Adding the switch to the project compiler command line worked!

Thank you so much for responding, this has been a great learning experience for me. If you want, I could try making a pull request updating the project to build on VS2019, or just make a small note in the readme mentioning the switch for those who may experience this same issue in the future.

Either way, I'll close this issue as it's now resolved. Thank you once again for your advice!
